// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekadtljxzeiiycdzpiot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrYWR0bGp4emVpaXljZHpwaW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzM5NTgsImV4cCI6MjA1ODY0OTk1OH0.LxYE46AqENmQNib0po0pA6Lcyp7Qm14CpV5XdMZ4NIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);